CREATE TABLE mensagem
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rementente   VARCHAR(255),
    destinatario VARCHAR(255),
    text         VARCHAR(255),
    anonimo_id   INT,
    psicologo_id INT,
    CONSTRAINT pk_mensagem PRIMARY KEY (id)
);

ALTER TABLE mensagem
    ADD CONSTRAINT FK_MENSAGEM_ON_ANONIMO FOREIGN KEY (anonimo_id) REFERENCES anonimo (id);

ALTER TABLE mensagem
    ADD CONSTRAINT FK_MENSAGEM_ON_PSICOLOGO FOREIGN KEY (psicologo_id) REFERENCES psicologo (id);