CREATE TABLE psicologo
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    email      VARCHAR(255),
    senha      VARCHAR(255),
    crp        VARCHAR(255),
    situacao   VARCHAR(255),
    usuario_id INT,
    CONSTRAINT pk_psicologo PRIMARY KEY (id)
);

ALTER TABLE psicologo
    ADD CONSTRAINT uc_psicologo_usuario UNIQUE (usuario_id);

ALTER TABLE psicologo
    ADD CONSTRAINT FK_PSICOLOGO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);