CREATE TABLE usuario
(
    id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    email         VARCHAR(255),
    senha         VARCHAR(255),
    data_cadastro TIMESTAMP,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);