CREATE TABLE anonimo
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    email      VARCHAR(255),
    senha      VARCHAR(255),
    usuario_id INT,
    CONSTRAINT pk_anonimo PRIMARY KEY (id)
);

ALTER TABLE anonimo
    ADD CONSTRAINT uc_anonimo_usuario UNIQUE (usuario_id);

ALTER TABLE anonimo
    ADD CONSTRAINT FK_ANONIMO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);